"""
Email Poller Module
Polls Gmail inbox via Gmail API (OAuth2) for vendor replies.
No MX record or DNS changes required.
"""

import os
import base64
import json
from datetime import datetime
from email.utils import parseaddr
from email.header import decode_header
from dotenv import load_dotenv

load_dotenv()

GMAIL_CREDENTIALS_FILE = os.getenv(
    "GMAIL_CREDENTIALS_FILE",
    os.path.join(os.path.dirname(__file__), "gmail_credentials.json"),
)
GMAIL_TOKEN_FILE = os.getenv(
    "GMAIL_TOKEN_FILE",
    os.path.join(os.path.dirname(__file__), "gmail_token.json"),
)
GMAIL_SCOPES = ["https://www.googleapis.com/auth/gmail.modify"]

db = None
Supplier = None
Message = None
NegotiationSession = None


def init_poller_db(database, supplier_model, message_model, session_model):
    global db, Supplier, Message, NegotiationSession
    db = database
    Supplier = supplier_model
    Message = message_model
    NegotiationSession = session_model


def _get_gmail_service():
    """
    Build and return an authenticated Gmail API service object.
    
    Supports two modes:
    - Local dev: reads gmail_token.json file (generated by gmail_auth.py)
    - Deployed (Render etc.): reads token from GMAIL_TOKEN_JSON env var
    """
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from googleapiclient.discovery import build

    creds = None

    # Priority 1: GMAIL_TOKEN_JSON env var (for deployed environments)
    token_json_str = os.getenv("GMAIL_TOKEN_JSON")
    if token_json_str:
        try:
            token_data = json.loads(token_json_str)
            creds = Credentials.from_authorized_user_info(token_data, GMAIL_SCOPES)
        except Exception as e:
            print(f"[EmailPoller] Failed to parse GMAIL_TOKEN_JSON env var: {e}")

    # Priority 2: Token file on disk (for local development)
    if not creds and os.path.exists(GMAIL_TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(GMAIL_TOKEN_FILE, GMAIL_SCOPES)

    if not creds:
        print(
            "[EmailPoller] No valid token found. "
            "Run 'python gmail_auth.py' locally, then set GMAIL_TOKEN_JSON env var on server."
        )
        return None

    # Refresh expired tokens silently (no browser needed)
    if not creds.valid:
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            # Update the file if it exists (local dev convenience)
            if os.path.exists(GMAIL_TOKEN_FILE):
                with open(GMAIL_TOKEN_FILE, "w") as f:
                    f.write(creds.to_json())
        else:
            print("[EmailPoller] Token is invalid and cannot be refreshed.")
            return None

    return build("gmail", "v1", credentials=creds)


def _decode_mime_header(header_value):
    if not header_value:
        return ""
    decoded_parts = decode_header(header_value)
    result = []
    for part, charset in decoded_parts:
        if isinstance(part, bytes):
            result.append(part.decode(charset or "utf-8", errors="replace"))
        else:
            result.append(part)
    return " ".join(result)


def _extract_body_from_payload(payload):
    """Recursively extract text/plain (preferred) or text/html body from Gmail API payload."""
    plain_body = ""
    html_body = ""

    if "parts" in payload:
        for part in payload["parts"]:
            mime = part.get("mimeType", "")
            if mime == "text/plain" and not plain_body:
                data = part.get("body", {}).get("data", "")
                if data:
                    plain_body = base64.urlsafe_b64decode(data).decode("utf-8", errors="replace")
            elif mime == "text/html" and not html_body:
                data = part.get("body", {}).get("data", "")
                if data:
                    html_body = base64.urlsafe_b64decode(data).decode("utf-8", errors="replace")
            elif mime.startswith("multipart/"):
                nested = _extract_body_from_payload(part)
                if nested:
                    if not plain_body and not html_body:
                        return nested
    else:
        mime = payload.get("mimeType", "")
        data = payload.get("body", {}).get("data", "")
        if data:
            decoded = base64.urlsafe_b64decode(data).decode("utf-8", errors="replace")
            if mime == "text/plain":
                plain_body = decoded
            elif mime == "text/html":
                html_body = decoded

    return plain_body or html_body


def _get_header(headers, name):
    """Get a specific header value from Gmail API headers list."""
    for h in headers:
        if h["name"].lower() == name.lower():
            return h["value"]
    return ""


def poll_inbox():
    """Poll Gmail inbox for unread vendor replies and process them."""
    if not db or not Supplier:
        print("[EmailPoller] Database not initialized, skipping poll")
        return

    from email_webhook import (
        parse_email_for_quote,
        find_supplier_by_email,
        create_message_from_email,
    )

    service = _get_gmail_service()
    if not service:
        return

    print(f"[{datetime.now()}] Polling Gmail inbox...")

    try:
        results = (
            service.users()
            .messages()
            .list(userId="me", q="is:unread", maxResults=20)
            .execute()
        )
        messages = results.get("messages", [])

        if not messages:
            print(f"[EmailPoller] No unread emails")
            return

        print(f"[EmailPoller] Found {len(messages)} unread email(s)")

        for msg_meta in messages:
            msg_id = msg_meta["id"]
            try:
                msg = (
                    service.users()
                    .messages()
                    .get(userId="me", id=msg_id, format="full")
                    .execute()
                )

                headers = msg.get("payload", {}).get("headers", [])
                from_raw = _get_header(headers, "From")
                subject = _decode_mime_header(_get_header(headers, "Subject"))
                _, from_addr = parseaddr(from_raw)

                # Mark as read immediately to prevent duplicate processing
                _mark_as_read(service, msg_id)

                body = _extract_body_from_payload(msg.get("payload", {}))

                if not body or not from_addr:
                    continue

                print(f"[EmailPoller] Processing email from {from_addr}: {subject}")

                supplier = find_supplier_by_email(from_addr)

                if not supplier:
                    print(f"[EmailPoller] No matching supplier for {from_addr}, skipping")
                    continue

                parsed_data = parse_email_for_quote(body, from_addr, subject)

                message_result = create_message_from_email(
                    supplier.id, parsed_data, body
                )

                if parsed_data.get("is_quote_response"):
                    try:
                        from notifications import create_vendor_response_notification

                        session = NegotiationSession.query.get(supplier.session_id)
                        create_vendor_response_notification(
                            vendor_name=supplier.company_name,
                            opportunity_title=(
                                session.opportunity_title
                                if session
                                else "Government Contract"
                            ),
                            session_id=supplier.session_id,
                            supplier_id=supplier.id,
                            round_number=supplier.negotiation_round,
                            opportunity_id=(
                                session.opportunity_id if session else None
                            ),
                        )
                    except Exception as e:
                        print(f"[EmailPoller] Failed to create notification: {e}")

                print(
                    f"[EmailPoller] Processed email from "
                    f"{supplier.company_name}: {message_result}"
                )

            except Exception as e:
                print(f"[EmailPoller] Error processing message {msg_id}: {e}")
                continue

        print(f"[{datetime.now()}] Inbox poll complete")

    except Exception as e:
        print(f"[EmailPoller] Error during poll: {e}")


def _mark_as_read(service, msg_id):
    """Remove the UNREAD label from a message."""
    try:
        service.users().messages().modify(
            userId="me",
            id=msg_id,
            body={"removeLabelIds": ["UNREAD"]},
        ).execute()
    except Exception as e:
        print(f"[EmailPoller] Failed to mark message {msg_id} as read: {e}")
